services:
  
  depot.db:
    image: postgres:latest
    container_name: depot.db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost"
      ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  depot.auth.db:
    image: depot.auth.migrations
    container_name: depot.auth.db
    build:
      context: .
      dockerfile: src/Depot.Auth.Migrations/Dockerfile
    environment:
      ConnectionStrings__Default: Host=depot.db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      depot.db:
        condition: service_healthy
  
  depot.auth:
    image: depot.auth
    container_name: depot.auth
    build:
      context: .
      dockerfile: src/Depot.Auth/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=depot.db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      - depot.auth.db
    
    ports:
      - "5000:8080"

volumes:
  data: